# 3 node network with Alice, Bob and Charlie nodes

############### Component settings ###############
quantum_device_settings: &qdevice_cfg
  num_qubits: 20

  # coherence times (ns)
  T1: 0
  T2: 0

  # gate execution times (ns)
  init_time: 0
  single_qubit_gate_time: 0
  two_qubit_gate_time: 0
  measure_time: 0

  # noise model (probability)
  single_qubit_gate_depolar_prob: 0.
  two_qubit_gate_depolar_prob: 0.


quantum_link_settings: &qlink_cfg
  # Fidelity of generated EPR pairs
  fidelity: 1
  # Chance to succeed generating an EPR pair per entanglement attempt cycle (probability)
  prob_success: 1
  # Duration of an entanglement attempt cycle (ns)
  t_cycle: 1e5


classical_link_settings: &clink_cfg
  # Duration for a classical message to transmit to another node (ns)
  delay: 0


############### Network ###############
stacks:
  - name: Alice
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Bob
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg

  - name: Charlie
    qdevice_typ: generic
    qdevice_cfg:
      <<: *qdevice_cfg


links:
  - stack1: Alice
    stack2: Bob
    typ: depolarise
    cfg:
      <<: *qlink_cfg
  - stack1: Alice
    stack2: Charlie
    typ: depolarise
    cfg:
      <<: *qlink_cfg
  - stack1: Bob
    stack2: Charlie
    typ: depolarise
    cfg:
      <<: *qlink_cfg


clinks:
  - stack1: Alice
    stack2: Bob
    typ: default
    cfg:
      <<: *clink_cfg
  - stack1: Alice
    stack2: Charlie
    typ: default
    cfg:
      <<: *clink_cfg
  - stack1: Bob
    stack2: Charlie
    typ: default
    cfg:
      <<: *clink_cfg
